import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const SEED_CUSTOMERS = [
  {
    id: 'CT26002600',
    no: 1,
    code: 'CT26002600',
    firstName: 'Nhat Huu Tuan',
    middleName: '',
    lastName: 'Dang',
    fullName: 'Nhat Huu Tuan Dang',
    phone: '+1 (714) 837-2395',
    email: 'tuannhat.n2@gmail.com',
    language: 'Vietnamese',
    howDoYouKnowUs: 'Refer by other client',
    whoReferClient: 'Linh Dang',
    teleSaleTeam: 'Tiger Truong',
    contactOwnerName: 'Khanh Nguyen',
    contactOwnerAvatar: 'KN',
    contactOwnerBg: 'bg-blue-600 text-white',
    supportAgent: 'Anya Nguyen (anya42@9)',
    acaAccountStatus: 'Uploaded - Waiting for Verification',
    status: 'Active',
    lastModifiedBy: 'Anya Nguyen',
    lastModifiedTime: '09/17/2026, 09:12',
    dob: '12/28/1995',
    ssn: '673-73-0055',
    familyRelationship: 'Self',
    gender: 'Male',
    immigrationStatus: 'Permanent Resident',
    alienNumber: '219802465',
    certificateNumber: 'IOE0921776907',
    dateExpired: '03/31/2036',
    household: '1 member',
    enrolledAddress: '4301 Laurel Pond Way, Raleigh, NC 27616',
    mailingAddress: '4301 Laurel Pond Way, Raleigh, NC 27616',
    state: 'North Carolina (NC)',
    streetAddress: '4301 Laurel Pond Way',
    city: 'Raleigh',
    postalCode: '27616',
    county: 'Wake County',
    career: 'Software Developer',
    theBestRateEmail: 'frankdang641@thebestrate.com',
    acaAccount: 'frankdang641@gmail.com',
    acaPass: 'Thebest@2026',
    acaStatusSpecial: '',
    acaAccountSpecial: '',
    acaPassSpecial: '',
    enrollCallRep: 'Agent Anya Nguyen',
    deal: {
      id: 'D26005033',
      code: 'D26005033',
      title: 'Non-CMS - Nhat H Dang - OB 10/2026 (NC)',
      shortTitle: 'Non-CMS - Nhat H Dang - OB...',
      pipeline: 'Obamacare 2026',
      stage: 'Ready to Enroll (Obamacare 2026)',
      carrier: 'BCBS',
      amount: '$0.00',
      closeDate: '10/31/2026',
      sellingState: 'North Carolina (NC)',
      dealOwnerName: 'Khanh Nguyen',
      dealOwnerAvatar: 'KN',
      dealOwnerBg: 'bg-blue-600 text-white',
      enrolledNpn: 'Anh Que Pham 20011862',
      brokerEffectiveDate: '2026-09-09',
      terminationDate: '2027-12-31',
      primaryMemberId: 'MID-98234710',
      saleSupportStatus: 'Completed',
      numberMember: 1,
      closedLostReason: '---',
    },
    document: {
      id: 'DOC-01',
      name: 'Nhat H Dang',
      initials: 'ND',
      contactOwner: 'Khanh Nguyen (khanhnguyen31@7)',
      files: [
        { category: 'consentFormText', name: 'Consent 2026_AQP - Nh...', fullName: 'Consent 2026_AQP - Nhat Dang.pdf', size: '682.4 KB', type: 'pdf' },
        { category: 'identity', name: 'IMG_4413.jpg', fullName: 'IMG_4413.jpg', size: '164 KB', type: 'image' },
        { category: 'identity', name: 'IMG_5618.jpeg', fullName: 'IMG_5618.jpeg', size: '197.5 KB', type: 'image' },
        { category: 'identity', name: 'CamScanner 4-21-26 08...', fullName: 'CamScanner 4-21-26 08.44.pdf', size: '138 KB', type: 'pdf' },
        { category: 'paymentInformation', name: 'IMG_6539.jpeg', fullName: 'IMG_6539.jpeg', size: '1.7 MB', type: 'image' },
      ],
    },
    ticket: {
      id: 'TC2600101',
      title: 'ACA account 2026',
      pipeline: 'ACA account',
      status: 'Uploaded - Waiting for Verification',
      stage: 'Waiting on verification',
      ticketOwner: 'Khanh Nguyen',
      serviceAgent: 'Anya Nguyen',
      dueDate: '09/22/2026',
      closeDate: '----------',
    },
    activities: [
      { id: 'act-001', type: 'Ticket Activity', actor: 'Anya Nguyen (anya42@9)', time: '09/17/2026, 09:12', summary: 'moved ticket ACA account 2026 to Uploaded - Waiting for Verification.' },
      { id: 'act-002', type: 'Ticket Activity', actor: 'Anya Nguyen (anya42@9)', time: '09/11/2026, 17:45', summary: 'moved ticket ACA account 2026 to VERIFIED.' },
      { id: 'act-003', type: 'Deal Activity', actor: 'Khanh Nguyen (khanhnguyen31@7)', time: '09/09/2026, 13:05', summary: 'created deal Non-CMS - Nhat H Dang - OB 10/2026 (NC)' },
    ],
  },
  {
    id: 'CT26002605',
    no: 2,
    code: 'CT26002605',
    firstName: 'Ly',
    middleName: 'Le',
    lastName: 'Do',
    fullName: 'Ly Le Do',
    phone: '+1 (317) 506-6912',
    email: 'lyledo912@gmail.com',
    language: 'Vietnamese',
    howDoYouKnowUs: 'Cold Call',
    whoReferClient: '',
    teleSaleTeam: 'Tiger Truong',
    contactOwnerName: 'The Best Rate Insurance',
    contactOwnerAvatar: 'TB',
    contactOwnerBg: 'bg-teal-700 text-white',
    supportAgent: 'Miranda Pham',
    acaAccountStatus: 'Ready to Enroll',
    status: 'Active',
    lastModifiedBy: 'Miranda Pham',
    lastModifiedTime: '09/18/2026, 00:31',
    dob: '08/15/1992',
    ssn: '542-12-8821',
    familyRelationship: 'Self',
    gender: 'Female',
    immigrationStatus: 'Permanent Resident',
    alienNumber: '310982341',
    certificateNumber: 'IOE118239012',
    dateExpired: '10/20/2035',
    household: '2 members',
    enrolledAddress: '7822 Meridian St, Indianapolis, IN 46260',
    mailingAddress: '7822 Meridian St, Indianapolis, IN 46260',
    state: 'Indiana (IN)',
    streetAddress: '7822 Meridian St',
    city: 'Indianapolis',
    postalCode: '46260',
    county: 'Marion County',
    career: 'Nail Technician',
    theBestRateEmail: 'lyledo@thebestrate.com',
    acaAccount: 'lyledo912@gmail.com',
    acaPass: 'LyDo@2026!',
    acaStatusSpecial: '',
    acaAccountSpecial: '',
    acaPassSpecial: '',
    enrollCallRep: 'Agent Miranda Pham',
    deal: {
      id: 'D26005032',
      code: 'D26005032',
      title: 'Non-CMS - Ly Le Do - OB 10/2026 (IN)',
      shortTitle: 'Non-CMS - Ly Le Do - OB...',
      pipeline: 'Obamacare 2026',
      stage: 'Ready to Enroll (Obamacare 2026)',
      carrier: 'Ambetter',
      amount: '$0.00',
      closeDate: '10/31/2026',
      sellingState: 'Indiana (IN)',
      dealOwnerName: 'The Best Rate Insurance',
      dealOwnerAvatar: 'TB',
      dealOwnerBg: 'bg-teal-700 text-white',
      enrolledNpn: 'Trono Truong 19823412',
      brokerEffectiveDate: '2026-09-10',
      terminationDate: '2027-12-31',
      primaryMemberId: 'MID-44120955',
      saleSupportStatus: 'Completed',
      numberMember: 2,
      closedLostReason: '---',
    },
    document: {
      id: 'DOC-02',
      name: 'Ly Le Do',
      initials: 'LD',
      contactOwner: 'The Best Rate Insurance',
      files: [
        { category: 'identity', name: 'DL_LyDo_Front.jpg', fullName: 'DL_LyDo_Front.jpg', size: '210 KB', type: 'image' },
        { category: 'consentFormText', name: 'Consent_LyDo_2026.pdf', fullName: 'Consent_LyDo_2026.pdf', size: '512 KB', type: 'pdf' },
      ],
    },
    ticket: {
      id: 'TC2600102',
      title: 'Collect Documents for Upload',
      pipeline: 'Upload documents',
      status: 'Open',
      stage: 'Waiting on document',
      ticketOwner: 'The Best Rate Insurance',
      serviceAgent: 'Miranda Pham',
      dueDate: '10/01/2026',
      closeDate: '----------',
    },
    activities: [
      { id: 'act-004', type: 'Deal Activity', actor: 'Miranda Pham', time: '09/18/2026, 00:31', summary: 'moved deal stage to Ready to Enroll (Obamacare 2026)' },
    ],
  },
  {
    id: 'CT26002604',
    no: 3,
    code: 'CT26002604',
    firstName: 'Thang',
    middleName: 'Van',
    lastName: 'Nguyen',
    fullName: 'Thang Van Nguyen',
    phone: '+1 (503) 819-5820',
    email: 'thang.nguyen582@yahoo.com',
    language: 'Vietnamese',
    howDoYouKnowUs: 'Cold Call',
    whoReferClient: '',
    teleSaleTeam: 'Tiger Truong',
    contactOwnerName: 'Trono Truong',
    contactOwnerAvatar: 'TT',
    contactOwnerBg: 'bg-amber-700 text-white',
    supportAgent: 'Sean Ngo',
    acaAccountStatus: 'Uploaded - Waiting for Verification',
    status: 'Active',
    lastModifiedBy: 'Trono Truong',
    lastModifiedTime: '09/17/2026, 21:47',
    dob: '05/22/1988',
    ssn: '531-90-4421',
    familyRelationship: 'Self',
    gender: 'Male',
    immigrationStatus: 'U.S. Citizen',
    alienNumber: '',
    certificateNumber: 'USC09918234',
    dateExpired: 'N/A',
    household: '3 members',
    enrolledAddress: '1240 SE Powell Blvd, Portland, OR 97202',
    mailingAddress: '1240 SE Powell Blvd, Portland, OR 97202',
    state: 'Oregon (OR)',
    streetAddress: '1240 SE Powell Blvd',
    city: 'Portland',
    postalCode: '97202',
    county: 'Multnomah County',
    career: 'Restaurant Owner',
    theBestRateEmail: '',
    acaAccount: 'thang.nguyen582@yahoo.com',
    acaPass: 'ThangNguyen#26',
    acaStatusSpecial: '',
    acaAccountSpecial: '',
    acaPassSpecial: '',
    enrollCallRep: 'Agent Sean Ngo',
    deal: {
      id: 'D26005031',
      code: 'D26005031',
      title: 'Non-CMS - Thang Nguyen - OB 10/2026 (OR)',
      shortTitle: 'Non-CMS - Thang Nguyen - OB...',
      pipeline: 'Obamacare 2026',
      stage: 'Uploaded - Waiting for Verification',
      carrier: 'Kaiser Permanente',
      amount: '$0.00',
      closeDate: '10/15/2026',
      sellingState: 'Oregon (OR)',
      dealOwnerName: 'Trono Truong',
      dealOwnerAvatar: 'TT',
      dealOwnerBg: 'bg-amber-700 text-white',
      enrolledNpn: 'Trono Truong 19823412',
      brokerEffectiveDate: '2026-09-12',
      terminationDate: '2027-12-31',
      primaryMemberId: 'MID-77812901',
      saleSupportStatus: 'In Review',
      numberMember: 3,
      closedLostReason: '---',
    },
    document: {
      id: 'DOC-03',
      name: 'Thang Van Nguyen',
      initials: 'TN',
      contactOwner: 'Trono Truong',
      files: [
        { category: 'identity', name: 'US_Passport_Thang.pdf', fullName: 'US_Passport_Thang.pdf', size: '1.2 MB', type: 'pdf' },
        { category: 'tax', name: '1040_TaxReturn_2025.pdf', fullName: '1040_TaxReturn_2025.pdf', size: '2.4 MB', type: 'pdf' },
      ],
    },
    ticket: {
      id: 'TC2600103',
      title: 'ACA account 2026 - Document Verification',
      pipeline: 'ACA account',
      status: 'Uploaded - Waiting for Verification',
      stage: 'Waiting on verification',
      ticketOwner: 'Trono Truong',
      serviceAgent: 'Sean Ngo',
      dueDate: '09/25/2026',
      closeDate: '----------',
    },
    activities: [
      { id: 'act-005', type: 'Ticket Activity', actor: 'Sean Ngo', time: '09/17/2026, 21:47', summary: 'updated ticket to Uploaded - Waiting for Verification' },
    ],
  },
  {
    id: 'CT26002603',
    no: 4,
    code: 'CT26002603',
    firstName: 'Oanh',
    middleName: 'Thi',
    lastName: 'Le',
    fullName: 'Oanh Thi Le',
    phone: '+1 (832) 441-2099',
    email: 'oanhle.tx@gmail.com',
    language: 'Vietnamese',
    howDoYouKnowUs: 'Social Media',
    whoReferClient: '',
    teleSaleTeam: 'Tiger Truong',
    contactOwnerName: 'Nathan Truong',
    contactOwnerAvatar: 'NT',
    contactOwnerBg: 'bg-amber-800 text-white',
    supportAgent: 'Sarah Thai',
    acaAccountStatus: 'VERIFIED',
    status: 'Active',
    lastModifiedBy: 'Celine Pham',
    lastModifiedTime: '09/17/2026, 18:51',
    dob: '11/04/1985',
    ssn: '462-88-1902',
    familyRelationship: 'Self',
    gender: 'Female',
    immigrationStatus: 'Permanent Resident',
    alienNumber: '098172635',
    certificateNumber: 'IOE088192019',
    dateExpired: '05/15/2034',
    household: '1 member',
    enrolledAddress: '11204 Bellaire Blvd, Houston, TX 77072',
    mailingAddress: '11204 Bellaire Blvd, Houston, TX 77072',
    state: 'Texas (TX)',
    streetAddress: '11204 Bellaire Blvd',
    city: 'Houston',
    postalCode: '77072',
    county: 'Harris County',
    career: 'Baker',
    theBestRateEmail: '',
    acaAccount: 'oanhle.tx@gmail.com',
    acaPass: 'Houston@2026',
    acaStatusSpecial: '',
    acaAccountSpecial: '',
    acaPassSpecial: '',
    enrollCallRep: 'Agent Sarah Thai',
    deal: {
      id: 'D26005030',
      code: 'D26005030',
      title: 'Non-CMS - Oanh Thi Le - OB 10/2026 (TX)',
      shortTitle: 'Non-CMS - Oanh Thi Le - OB...',
      pipeline: 'Obamacare 2026',
      stage: 'Enrolled - Active (Obamacare 2026)',
      carrier: 'UnitedHealthcare',
      amount: '$250.00',
      closeDate: '09/30/2026',
      sellingState: 'Texas (TX)',
      dealOwnerName: 'Nathan Truong',
      dealOwnerAvatar: 'NT',
      dealOwnerBg: 'bg-amber-800 text-white',
      enrolledNpn: 'Anh Que Pham 20011862',
      brokerEffectiveDate: '2026-09-01',
      terminationDate: '2027-12-31',
      primaryMemberId: 'MID-99214022',
      saleSupportStatus: 'Completed',
      numberMember: 1,
      closedLostReason: '---',
    },
    document: {
      id: 'DOC-04',
      name: 'Oanh Thi Le',
      initials: 'OL',
      contactOwner: 'Nathan Truong',
      files: [
        { category: 'identity', name: 'GreenCard_OanhLe.jpg', fullName: 'GreenCard_OanhLe.jpg', size: '340 KB', type: 'image' },
        { category: 'paymentInformation', name: 'VoidCheck_Chase.pdf', fullName: 'VoidCheck_Chase.pdf', size: '180 KB', type: 'pdf' },
      ],
    },
    ticket: {
      id: 'TC2600104',
      title: 'ACA account 2026',
      pipeline: 'ACA account',
      status: 'VERIFIED',
      stage: 'Completed',
      ticketOwner: 'Nathan Truong',
      serviceAgent: 'Sarah Thai',
      dueDate: '09/20/2026',
      closeDate: '09/17/2026',
    },
    activities: [
      { id: 'act-006', type: 'Deal Activity', actor: 'Sarah Thai', time: '09/17/2026, 18:51', summary: 'marked deal as Enrolled - Active (Obamacare 2026)' },
    ],
  },
  {
    id: 'CT26002602',
    no: 5,
    code: 'CT26002602',
    firstName: 'Thi',
    middleName: 'Tra My',
    lastName: 'Vo',
    fullName: 'Thi Tra My Vo',
    phone: '+1 (731) 444-9992',
    email: 'ivyvo91570@gmail.com',
    language: 'Vietnamese',
    howDoYouKnowUs: 'Friend Referral',
    whoReferClient: 'Thao Tran',
    teleSaleTeam: 'Tiger Truong',
    contactOwnerName: 'Nancy Pham',
    contactOwnerAvatar: 'NP',
    contactOwnerBg: 'bg-purple-600 text-white',
    supportAgent: 'Darwin Bui',
    acaAccountStatus: 'Ready to Enroll',
    status: 'Active',
    lastModifiedBy: 'Darwin Bui',
    lastModifiedTime: '09/17/2026, 17:30',
    dob: '09/15/1990',
    ssn: '429-33-8812',
    familyRelationship: 'Self',
    gender: 'Female',
    immigrationStatus: 'Permanent Resident',
    alienNumber: '293817264',
    certificateNumber: 'IOE092817263',
    dateExpired: '08/20/2033',
    household: '2 members',
    enrolledAddress: '5510 Poplar Ave, Memphis, TN 38119',
    mailingAddress: '5510 Poplar Ave, Memphis, TN 38119',
    state: 'Tennessee (TN)',
    streetAddress: '5510 Poplar Ave',
    city: 'Memphis',
    postalCode: '38119',
    county: 'Shelby County',
    career: 'Hairstylist',
    theBestRateEmail: '',
    acaAccount: 'ivyvo91570@gmail.com',
    acaPass: 'IvyVo@2026',
    acaStatusSpecial: '',
    acaAccountSpecial: '',
    acaPassSpecial: '',
    enrollCallRep: 'Agent Darwin Bui',
    deal: {
      id: 'D26005029',
      code: 'D26005029',
      title: 'Non-CMS - Thi Tra My Vo - OB 10/2026 (TN)',
      shortTitle: 'Non-CMS - Thi Tra My Vo - OB...',
      pipeline: 'Obamacare 2026',
      stage: 'Ready to Enroll (Obamacare 2026)',
      carrier: 'BCBS',
      amount: '$0.00',
      closeDate: '10/20/2026',
      sellingState: 'Tennessee (TN)',
      dealOwnerName: 'Nancy Pham',
      dealOwnerAvatar: 'NP',
      dealOwnerBg: 'bg-purple-600 text-white',
      enrolledNpn: 'Nancy Pham 20491823',
      brokerEffectiveDate: '2026-09-14',
      terminationDate: '2027-12-31',
      primaryMemberId: 'MID-66381920',
      saleSupportStatus: 'Completed',
      numberMember: 2,
      closedLostReason: '---',
    },
    document: {
      id: 'DOC-05',
      name: 'Thi Tra My Vo',
      initials: 'TV',
      contactOwner: 'Nancy Pham',
      files: [
        { category: 'identity', name: 'StateID_TraMyVo.jpg', fullName: 'StateID_TraMyVo.jpg', size: '280 KB', type: 'image' },
        { category: 'consentFormText', name: 'Consent_TraMyVo.pdf', fullName: 'Consent_TraMyVo.pdf', size: '640 KB', type: 'pdf' },
      ],
    },
    ticket: {
      id: 'TC2600105',
      title: 'Prepare Enrollment Package',
      pipeline: 'Client Support',
      status: 'In Progress',
      stage: 'Ready to enroll',
      ticketOwner: 'Nancy Pham',
      serviceAgent: 'Darwin Bui',
      dueDate: '09/28/2026',
      closeDate: '----------',
    },
    activities: [
      { id: 'act-007', type: 'Deal Activity', actor: 'Darwin Bui', time: '09/17/2026, 17:30', summary: 'set stage to Ready to Enroll (Obamacare 2026)' },
    ],
  },
  {
    id: 'CT26002601',
    no: 6,
    code: 'CT26002601',
    firstName: 'Duc',
    middleName: 'Huu',
    lastName: 'Pham',
    fullName: 'Duc Huu Pham',
    phone: '+1 (346) 401-1971',
    email: 'phuc3684@gmail.com',
    language: 'Vietnamese',
    howDoYouKnowUs: 'Existing Network',
    whoReferClient: '',
    teleSaleTeam: 'Tiger Truong',
    contactOwnerName: 'Jay Ly',
    contactOwnerAvatar: 'JL',
    contactOwnerBg: 'bg-cyan-700 text-white',
    supportAgent: 'Ivy Le',
    acaAccountStatus: 'Enrolled',
    status: 'Active',
    lastModifiedBy: 'Jay Ly',
    lastModifiedTime: '09/17/2026, 16:51',
    dob: '02/10/1980',
    ssn: '450-99-2810',
    familyRelationship: 'Self',
    gender: 'Male',
    immigrationStatus: 'U.S. Citizen',
    alienNumber: '',
    certificateNumber: 'USC08827163',
    dateExpired: 'N/A',
    household: '4 members',
    enrolledAddress: '9720 Coit Rd, Dallas, TX 75240',
    mailingAddress: '9720 Coit Rd, Dallas, TX 75240',
    state: 'Texas (TX)',
    streetAddress: '9720 Coit Rd',
    city: 'Dallas',
    postalCode: '75240',
    county: 'Dallas County',
    career: 'Electrician',
    theBestRateEmail: '',
    acaAccount: 'phuc3684@gmail.com',
    acaPass: 'DallasTX@2026',
    acaStatusSpecial: '',
    acaAccountSpecial: '',
    acaPassSpecial: '',
    enrollCallRep: 'Agent Jay Ly',
    deal: {
      id: 'D26005028',
      code: 'D26005028',
      title: 'Non-CMS - Duc Huu Pham - OB 10/2026 (TX)',
      shortTitle: 'Non-CMS - Duc Huu Pham - OB...',
      pipeline: 'Obamacare 2026',
      stage: 'Enrolled - 1st Payment done (Obamacare 2026)',
      carrier: 'Molina Healthcare',
      amount: '$180.00',
      closeDate: '09/15/2026',
      sellingState: 'Texas (TX)',
      dealOwnerName: 'Jay Ly',
      dealOwnerAvatar: 'JL',
      dealOwnerBg: 'bg-cyan-700 text-white',
      enrolledNpn: 'Anh Que Pham 20011862',
      brokerEffectiveDate: '2026-09-01',
      terminationDate: '2027-12-31',
      primaryMemberId: 'MID-55291823',
      saleSupportStatus: 'Completed',
      numberMember: 4,
      closedLostReason: '---',
    },
    document: {
      id: 'DOC-06',
      name: 'Duc Huu Pham',
      initials: 'DP',
      contactOwner: 'Jay Ly',
      files: [
        { category: 'identity', name: 'US_Certificate_DucPham.pdf', fullName: 'US_Certificate_DucPham.pdf', size: '890 KB', type: 'pdf' },
        { category: 'insuranceRecord', name: 'Molina_Policy_Confirmation.pdf', fullName: 'Molina_Policy_Confirmation.pdf', size: '420 KB', type: 'pdf' },
      ],
    },
    ticket: {
      id: 'TC2600106',
      title: 'First Premium Payment Followup',
      pipeline: 'Client Support',
      status: 'Closed',
      stage: 'Payment done',
      ticketOwner: 'Jay Ly',
      serviceAgent: 'Ivy Le',
      dueDate: '09/16/2026',
      closeDate: '09/15/2026',
    },
    activities: [
      { id: 'act-008', type: 'Deal Activity', actor: 'Jay Ly', time: '09/17/2026, 16:51', summary: 'first payment verified, stage moved to Enrolled - 1st Payment done' },
    ],
  },
  {
    id: 'CT26002599',
    no: 7,
    code: 'CT26002599',
    firstName: 'Phuong',
    middleName: 'Trang',
    lastName: 'Huynh',
    fullName: 'Phuong Trang Huynh',
    phone: '+1 (713) 474-6904',
    email: 'tranghuynh.hou@yahoo.com',
    language: 'Vietnamese',
    howDoYouKnowUs: 'Cold Call',
    whoReferClient: '',
    teleSaleTeam: 'Tiger Truong',
    contactOwnerName: 'Hano Ngo',
    contactOwnerAvatar: 'HN',
    contactOwnerBg: 'bg-blue-500 text-white',
    supportAgent: 'Anya Nguyen',
    acaAccountStatus: 'Need Create ACA Account',
    status: 'Inactive',
    lastModifiedBy: 'Miranda Pham',
    lastModifiedTime: '09/17/2026, 15:10',
    dob: '06/30/1959',
    ssn: '439-01-7729',
    familyRelationship: 'Self',
    gender: 'Female',
    immigrationStatus: 'Permanent Resident',
    alienNumber: '192837465',
    certificateNumber: 'IOE091827364',
    dateExpired: '11/12/2032',
    household: '1 member',
    enrolledAddress: '2300 S Lamar Blvd, Austin, TX 78704',
    mailingAddress: '2300 S Lamar Blvd, Austin, TX 78704',
    state: 'Texas (TX)',
    streetAddress: '2300 S Lamar Blvd',
    city: 'Austin',
    postalCode: '78704',
    county: 'Travis County',
    career: 'Retired',
    theBestRateEmail: '',
    acaAccount: 'tranghuynh.hou@yahoo.com',
    acaPass: 'AustinMedicare@26',
    acaStatusSpecial: '',
    acaAccountSpecial: '',
    acaPassSpecial: '',
    enrollCallRep: 'Agent Miranda Pham',
    deal: {
      id: 'D26005027',
      code: 'D26005027',
      title: 'Medicare Advantage - Phuong Trang Huynh - 2026 (TX)',
      shortTitle: 'Medicare Advantage - Phuong Trang...',
      pipeline: 'Medicare 2026',
      stage: 'Ready to Enroll (Medicare 2026)',
      carrier: 'Humana',
      amount: '$320.00',
      closeDate: '10/10/2026',
      sellingState: 'Texas (TX)',
      dealOwnerName: 'Miranda Pham',
      dealOwnerAvatar: 'MP',
      dealOwnerBg: 'bg-rose-400 text-white',
      enrolledNpn: 'Anh Que Pham 20011862',
      brokerEffectiveDate: '2026-10-01',
      terminationDate: '2027-12-31',
      primaryMemberId: 'MID-11928340',
      saleSupportStatus: 'Completed',
      numberMember: 1,
      closedLostReason: '---',
    },
    document: {
      id: 'DOC-07',
      name: 'Phuong Trang Huynh',
      initials: 'PH',
      contactOwner: 'Miranda Pham',
      files: [
        { category: 'identity', name: 'Medicare_Card_PhuongHuynh.jpg', fullName: 'Medicare_Card_PhuongHuynh.jpg', size: '410 KB', type: 'image' },
        { category: 'consentFormText', name: 'SOA_Form_Signed.pdf', fullName: 'SOA_Form_Signed.pdf', size: '580 KB', type: 'pdf' },
      ],
    },
    ticket: {
      id: 'TC2600107',
      title: 'Medicare SOA Scope of Appointment Verification',
      pipeline: 'Client Support',
      status: 'Open',
      stage: 'Waiting on verification',
      ticketOwner: 'Miranda Pham',
      serviceAgent: 'Anya Nguyen',
      dueDate: '10/05/2026',
      closeDate: '----------',
    },
    activities: [
      { id: 'act-009', type: 'Deal Activity', actor: 'Miranda Pham', time: '09/17/2026, 15:10', summary: 'created deal Medicare Advantage - Phuong Trang Huynh - 2026 (TX)' },
    ],
  },
  {
    id: 'CT26002598',
    no: 8,
    code: 'CT26002598',
    firstName: 'Minh',
    middleName: 'Tuan',
    lastName: 'Vu',
    fullName: 'Minh Tuan Vu',
    phone: '+1 (408) 332-9118',
    email: 'minhtuan.vu@gmail.com',
    language: 'Vietnamese',
    howDoYouKnowUs: 'Facebook Ad',
    whoReferClient: '',
    teleSaleTeam: 'Tiger Truong',
    contactOwnerName: 'Khanh Nguyen',
    contactOwnerAvatar: 'KN',
    contactOwnerBg: 'bg-blue-600 text-white',
    supportAgent: 'Sean Ngo',
    acaAccountStatus: 'Pending',
    status: 'Active',
    lastModifiedBy: 'Khanh Nguyen',
    lastModifiedTime: '09/16/2026, 14:22',
    dob: '04/18/1993',
    ssn: '567-44-1290',
    familyRelationship: 'Self',
    gender: 'Male',
    immigrationStatus: 'Permanent Resident',
    alienNumber: '392817263',
    certificateNumber: 'IOE088192039',
    dateExpired: '01/15/2035',
    household: '1 member',
    enrolledAddress: '1620 Tully Rd, San Jose, CA 95122',
    mailingAddress: '1620 Tully Rd, San Jose, CA 95122',
    state: 'California (CA)',
    streetAddress: '1620 Tully Rd',
    city: 'San Jose',
    postalCode: '95122',
    county: 'Santa Clara County',
    career: 'Uber Driver',
    theBestRateEmail: '',
    acaAccount: 'minhtuan.vu@gmail.com',
    acaPass: 'SanJose@2026',
    acaStatusSpecial: '',
    acaAccountSpecial: '',
    acaPassSpecial: '',
    enrollCallRep: 'Agent Sean Ngo',
    deal: {
      id: 'D26005026',
      code: 'D26005026',
      title: 'Individual Plan - Minh Tuan Vu - 2026 (CA)',
      shortTitle: 'Individual Plan - Minh Tuan Vu...',
      pipeline: 'Obamacare 2026',
      stage: 'New Opportunity/Call to Renew (Obamacare 2026)',
      carrier: 'Blue Shield of California',
      amount: '$0.00',
      closeDate: '11/01/2026',
      sellingState: 'California (CA)',
      dealOwnerName: 'Khanh Nguyen',
      dealOwnerAvatar: 'KN',
      dealOwnerBg: 'bg-blue-600 text-white',
      enrolledNpn: 'Anh Que Pham 20011862',
      brokerEffectiveDate: '2026-11-01',
      terminationDate: '2027-12-31',
      primaryMemberId: 'MID-88192019',
      saleSupportStatus: 'Initial',
      numberMember: 1,
      closedLostReason: '---',
    },
    document: {
      id: 'DOC-08',
      name: 'Minh Tuan Vu',
      initials: 'MV',
      contactOwner: 'Khanh Nguyen',
      files: [
        { category: 'identity', name: 'CA_DriverLicense_MinhVu.jpg', fullName: 'CA_DriverLicense_MinhVu.jpg', size: '290 KB', type: 'image' },
      ],
    },
    ticket: {
      id: 'TC2600108',
      title: 'New Lead Outreach Call',
      pipeline: 'Client Support',
      status: 'Open',
      stage: 'Need contact',
      ticketOwner: 'Khanh Nguyen',
      serviceAgent: 'Sean Ngo',
      dueDate: '09/25/2026',
      closeDate: '----------',
    },
    activities: [
      { id: 'act-010', type: 'Deal Activity', actor: 'Khanh Nguyen', time: '09/16/2026, 14:22', summary: 'new deal opportunity created for Covered California' },
    ],
  },
  {
    id: 'CT26002597',
    no: 9,
    code: 'CT26002597',
    firstName: 'Kieu',
    middleName: 'Loan',
    lastName: 'Tran',
    fullName: 'Kieu Loan Tran',
    phone: '+1 (404) 778-2910',
    email: 'kieuloan.atl@gmail.com',
    language: 'Vietnamese',
    howDoYouKnowUs: 'Google Search',
    whoReferClient: '',
    teleSaleTeam: 'Tiger Truong',
    contactOwnerName: 'Trono Truong',
    contactOwnerAvatar: 'TT',
    contactOwnerBg: 'bg-amber-700 text-white',
    supportAgent: 'Sarah Thai',
    acaAccountStatus: 'Pending - Waiting for Document',
    status: 'Inactive',
    lastModifiedBy: 'Sarah Thai',
    lastModifiedTime: '09/15/2026, 11:05',
    dob: '07/19/1987',
    ssn: '419-55-9018',
    familyRelationship: 'Self',
    gender: 'Female',
    immigrationStatus: 'Permanent Resident',
    alienNumber: '482910293',
    certificateNumber: 'IOE091823901',
    dateExpired: '09/01/2035',
    household: '2 members',
    enrolledAddress: '5400 Buford Hwy NE, Atlanta, GA 30340',
    mailingAddress: '5400 Buford Hwy NE, Atlanta, GA 30340',
    state: 'Georgia (GA)',
    streetAddress: '5400 Buford Hwy NE',
    city: 'Atlanta',
    postalCode: '30340',
    county: 'DeKalb County',
    career: 'Accountant',
    theBestRateEmail: '',
    acaAccount: 'kieuloan.atl@gmail.com',
    acaPass: 'AtlantaLoan@2026',
    acaStatusSpecial: '',
    acaAccountSpecial: '',
    acaPassSpecial: '',
    enrollCallRep: 'Agent Sarah Thai',
    deal: {
      id: 'D26005025',
      code: 'D26005025',
      title: 'Non-CMS - Kieu Loan Tran - OB 2026 (GA)',
      shortTitle: 'Non-CMS - Kieu Loan Tran - OB...',
      pipeline: 'Obamacare 2026',
      stage: 'Enrolled - Active (Obamacare 2026)',
      carrier: 'Oscar',
      amount: '$145.00',
      closeDate: '09/28/2026',
      sellingState: 'Georgia (GA)',
      dealOwnerName: 'Trono Truong',
      dealOwnerAvatar: 'TT',
      dealOwnerBg: 'bg-amber-700 text-white',
      enrolledNpn: 'Trono Truong 19823412',
      brokerEffectiveDate: '2026-09-01',
      terminationDate: '2027-12-31',
      primaryMemberId: 'MID-77382910',
      saleSupportStatus: 'Completed',
      numberMember: 2,
      closedLostReason: '---',
    },
    document: {
      id: 'DOC-09',
      name: 'Kieu Loan Tran',
      initials: 'KT',
      contactOwner: 'Trono Truong',
      files: [
        { category: 'identity', name: 'Georgia_ID_KieuLoan.jpg', fullName: 'Georgia_ID_KieuLoan.jpg', size: '220 KB', type: 'image' },
        { category: 'tax', name: 'W2_Form_2025.pdf', fullName: 'W2_Form_2025.pdf', size: '480 KB', type: 'pdf' },
      ],
    },
    ticket: {
      id: 'TC2600109',
      title: 'ACA account 2026',
      pipeline: 'ACA account',
      status: 'VERIFIED',
      stage: 'Completed',
      ticketOwner: 'Trono Truong',
      serviceAgent: 'Sarah Thai',
      dueDate: '09/20/2026',
      closeDate: '09/15/2026',
    },
    activities: [
      { id: 'act-011', type: 'Deal Activity', actor: 'Sarah Thai', time: '09/15/2026, 11:05', summary: 'policy activated, status changed to Enrolled - Active' },
    ],
  },
  {
    id: 'CT26002596',
    no: 10,
    code: 'CT26002596',
    firstName: 'Bao',
    middleName: 'Quoc',
    lastName: 'Hoang',
    fullName: 'Bao Quoc Hoang',
    phone: '+1 (206) 881-4920',
    email: 'bao.hoang.sea@yahoo.com',
    language: 'Vietnamese',
    howDoYouKnowUs: 'Refer by other client',
    whoReferClient: 'Quang Hoang',
    teleSaleTeam: 'Tiger Truong',
    contactOwnerName: 'Jay Ly',
    contactOwnerAvatar: 'JL',
    contactOwnerBg: 'bg-cyan-700 text-white',
    supportAgent: 'Ivy Le',
    acaAccountStatus: 'Waiting for document',
    status: 'Active',
    lastModifiedBy: 'Ivy Le',
    lastModifiedTime: '09/14/2026, 09:40',
    dob: '03/12/1982',
    ssn: '512-88-7741',
    familyRelationship: 'Self',
    gender: 'Male',
    immigrationStatus: 'Permanent Resident',
    alienNumber: '591827364',
    certificateNumber: 'IOE081928374',
    dateExpired: '04/10/2034',
    household: '3 members',
    enrolledAddress: '6710 Martin Luther King Jr Way S, Seattle, WA 98118',
    mailingAddress: '6710 Martin Luther King Jr Way S, Seattle, WA 98118',
    state: 'Washington (WA)',
    streetAddress: '6710 Martin Luther King Jr Way S',
    city: 'Seattle',
    postalCode: '98118',
    county: 'King County',
    career: 'Machinist',
    theBestRateEmail: '',
    acaAccount: 'bao.hoang.sea@yahoo.com',
    acaPass: 'SeattleBao#2026',
    acaStatusSpecial: '',
    acaAccountSpecial: '',
    acaPassSpecial: '',
    enrollCallRep: 'Agent Ivy Le',
    deal: {
      id: 'D26005024',
      code: 'D26005024',
      title: 'Non-CMS - Bao Quoc Hoang - OB 2026 (WA)',
      shortTitle: 'Non-CMS - Bao Quoc Hoang - OB...',
      pipeline: 'Obamacare 2026',
      stage: 'Waiting for document (Obamacare 2026)',
      carrier: 'Premera Blue Cross',
      amount: '$0.00',
      closeDate: '10/25/2026',
      sellingState: 'Washington (WA)',
      dealOwnerName: 'Jay Ly',
      dealOwnerAvatar: 'JL',
      dealOwnerBg: 'bg-cyan-700 text-white',
      enrolledNpn: 'Anh Que Pham 20011862',
      brokerEffectiveDate: '2026-10-01',
      terminationDate: '2027-12-31',
      primaryMemberId: 'MID-33918274',
      saleSupportStatus: 'Waiting Document',
      numberMember: 3,
      closedLostReason: '---',
    },
    document: {
      id: 'DOC-10',
      name: 'Bao Quoc Hoang',
      initials: 'BH',
      contactOwner: 'Jay Ly',
      files: [
        { category: 'identity', name: 'WA_DriverLicense_BaoHoang.jpg', fullName: 'WA_DriverLicense_BaoHoang.jpg', size: '310 KB', type: 'image' },
      ],
    },
    ticket: {
      id: 'TC2600110',
      title: 'Collect Income Verification Document',
      pipeline: 'Upload documents',
      status: 'Open',
      stage: 'Waiting on contact',
      ticketOwner: 'Jay Ly',
      serviceAgent: 'Ivy Le',
      dueDate: '09/30/2026',
      closeDate: '----------',
    },
    activities: [
      { id: 'act-012', type: 'Ticket Activity', actor: 'Ivy Le', time: '09/14/2026, 09:40', summary: 'sent reminder to client to upload 2025 tax or pay stub' },
    ],
  },
];

async function main() {
  console.log('🌱 Starting CRM database seeding...');

  // Clean old records
  await prisma.activity.deleteMany({});
  await prisma.note.deleteMany({});
  await prisma.task.deleteMany({});
  await prisma.ticket.deleteMany({});
  await prisma.documentFile.deleteMany({});
  await prisma.customerDocument.deleteMany({});
  await prisma.deal.deleteMany({});
  await prisma.contact.deleteMany({});

  console.log('🧹 Cleaned existing records.');

  for (const c of SEED_CUSTOMERS) {
    const { deal, document, ticket, activities, ...contactFields } = c;

    // 1. Create Contact
    const createdContact = await prisma.contact.create({
      data: contactFields,
    });

    // 2. Create Deal
    if (deal) {
      await prisma.deal.create({
        data: {
          ...deal,
          contactId: createdContact.id,
        },
      });
    }

    // 3. Create Document with files
    if (document) {
      const { files, ...docData } = document;
      const createdDoc = await prisma.customerDocument.create({
        data: {
          ...docData,
          contactId: createdContact.id,
        },
      });

      if (files && files.length > 0) {
        for (const file of files) {
          await prisma.documentFile.create({
            data: {
              ...file,
              documentId: createdDoc.id,
            },
          });
        }
      }
    }

    // 4. Create Ticket
    if (ticket) {
      await prisma.ticket.create({
        data: {
          ...ticket,
          contactId: createdContact.id,
          dealId: deal ? deal.id : null,
        },
      });
    }

    // 5. Create Activities
    if (activities && activities.length > 0) {
      for (const act of activities) {
        await prisma.activity.create({
          data: {
            ...act,
            contactId: createdContact.id,
            dealId: deal ? deal.id : null,
          },
        });
      }
    }

    console.log(`✅ Seeded Contact: [${createdContact.code}] ${createdContact.fullName}`);
  }

  // Fetch all contacts and deals to create more sample data
  const allContacts = await prisma.contact.findMany();
  const allDeals = await prisma.deal.findMany();

  if (allContacts.length > 0 && allDeals.length > 0) {
    console.log('Generating additional sample deals, tickets, tasks and commissions...');
    
    // Create Additional Realistic Deals across Medicare & Obamacare
    const extraDealsData = [
      {
        id: 'D26005040',
        code: 'D26005040',
        title: 'Medicare Advantage - Quyen Le - 2026 (TX)',
        shortTitle: 'Medicare - Quyen Le...',
        pipeline: 'Medicare 2026',
        stage: 'Enrolled - HRA Done - Active (Medicare 2026)',
        carrier: 'Humana',
        amount: '$350.00',
        closeDate: '10/12/2026',
        sellingState: 'Texas (TX)',
        dealOwnerName: 'Quyen Le',
        enrolledNpn: 'Quyen Le 20491823',
        brokerEffectiveDate: '2026-09-01',
        terminationDate: '2027-12-31',
        primaryMemberId: 'MID-77182901',
        saleSupportStatus: 'Completed',
        numberMember: 1,
        consentFormStatus: 'Uploaded',
      },
      {
        id: 'D26005041',
        code: 'D26005041',
        title: 'Medicare Supplement - Tri Tran - 2026 (CA)',
        shortTitle: 'Medicare - Tri Tran...',
        pipeline: 'Medicare 2026',
        stage: 'Auto Renew - Active (Medicare 2026)',
        carrier: 'UHC',
        amount: '$280.00',
        closeDate: '10/05/2026',
        sellingState: 'California (CA)',
        dealOwnerName: 'Tri Tran',
        enrolledNpn: 'Tri Tran 19823412',
        brokerEffectiveDate: '2026-09-10',
        terminationDate: '2027-12-31',
        primaryMemberId: 'MID-88192033',
        saleSupportStatus: 'Completed',
        numberMember: 1,
        consentFormStatus: 'Collected',
      },
      {
        id: 'D26005042',
        code: 'D26005042',
        title: 'Medicare Advantage - Jay Ly - 2026 (FL)',
        shortTitle: 'Medicare - Jay Ly...',
        pipeline: 'Medicare 2026',
        stage: 'Enrolled - Active (Medicare 2026)',
        carrier: 'Aetna',
        amount: '$310.00',
        closeDate: '09/28/2026',
        sellingState: 'Florida (FL)',
        dealOwnerName: 'Jay Ly',
        enrolledNpn: 'Jay Ly 20011862',
        brokerEffectiveDate: '2026-09-05',
        terminationDate: '2027-12-31',
        primaryMemberId: 'MID-11029384',
        saleSupportStatus: 'Completed',
        numberMember: 1,
        consentFormStatus: 'Sent out',
      },
      {
        id: 'D26005043',
        code: 'D26005043',
        title: 'Medicare Advantage - Ivy Le - 2026 (NC)',
        shortTitle: 'Medicare - Ivy Le...',
        pipeline: 'Medicare 2026',
        stage: 'Deal Lost (Medicare 2026)',
        carrier: 'BCBS',
        amount: '$0.00',
        closeDate: '09/15/2026',
        sellingState: 'North Carolina (NC)',
        dealOwnerName: 'Ivy Le',
        enrolledNpn: 'Anh Que Pham 20011862',
        brokerEffectiveDate: '2026-09-01',
        terminationDate: '2027-12-31',
        primaryMemberId: '',
        saleSupportStatus: 'NONE',
        numberMember: 1,
        closedLostReason: 'Client chose competitor',
        consentFormStatus: 'Existing client',
      },
      {
        id: 'D26005044',
        code: 'D26005044',
        title: 'OB 2026 - Sean Ngo - Enrolled Active (GA)',
        shortTitle: 'OB - Sean Ngo...',
        pipeline: 'Obamacare 2026',
        stage: 'Enrolled - Active (Obamacare 2026)',
        carrier: 'Ambetter',
        amount: '$190.00',
        closeDate: '10/01/2026',
        sellingState: 'Georgia (GA)',
        dealOwnerName: 'Sean Ngo',
        enrolledNpn: 'Sean Ngo 20991823',
        brokerEffectiveDate: '2026-09-01',
        terminationDate: '2027-12-31',
        primaryMemberId: 'MID-44910293',
        saleSupportStatus: 'Completed',
        numberMember: 2,
        consentFormStatus: 'Collected',
      },
      {
        id: 'D26005045',
        code: 'D26005045',
        title: 'OB 2026 - Ivy Le - Termination (TX)',
        shortTitle: 'OB - Ivy Le...',
        pipeline: 'Obamacare 2026',
        stage: 'Termination (Obamacare 2026)',
        carrier: 'Molina Healthcare',
        amount: '$0.00',
        closeDate: '09/10/2026',
        sellingState: 'Texas (TX)',
        dealOwnerName: 'Ivy Le',
        enrolledNpn: 'Ivy Le 19823412',
        brokerEffectiveDate: '2026-08-01',
        terminationDate: '2026-09-10',
        primaryMemberId: 'MID-33910294',
        saleSupportStatus: 'NONE',
        numberMember: 1,
        closedLostReason: 'Non-payment',
        consentFormStatus: 'Uploaded',
      },
      {
        id: 'D26005046',
        code: 'D26005046',
        title: 'OB 2026 - Sarah Thai - Deal Lost (FL)',
        shortTitle: 'OB - Sarah Thai...',
        pipeline: 'Obamacare 2026',
        stage: 'Deal Lost (Obamacare 2026)',
        carrier: 'Oscar',
        amount: '$0.00',
        closeDate: '09/05/2026',
        sellingState: 'Florida (FL)',
        dealOwnerName: 'Sarah Thai',
        enrolledNpn: 'Sarah Thai 20119283',
        brokerEffectiveDate: '2026-09-01',
        terminationDate: '2027-12-31',
        primaryMemberId: '',
        saleSupportStatus: 'NONE',
        numberMember: 1,
        closedLostReason: 'Income over limit',
        consentFormStatus: 'Need send new form',
      },
      {
        id: 'D26005047',
        code: 'D26005047',
        title: 'OB 2026 - Anya Nguyen - Active Policy (NC)',
        shortTitle: 'OB - Anya Nguyen...',
        pipeline: 'Obamacare 2026',
        stage: 'Enrolled - Active (Obamacare 2026)',
        carrier: 'BCBS',
        amount: '$220.00',
        closeDate: '09/20/2026',
        sellingState: 'North Carolina (NC)',
        dealOwnerName: 'Anya Nguyen',
        enrolledNpn: 'Anya Nguyen 20188212',
        brokerEffectiveDate: '2026-09-01',
        terminationDate: '2027-12-31',
        primaryMemberId: 'MID-88291024',
        saleSupportStatus: 'Completed',
        numberMember: 1,
        consentFormStatus: 'Collected',
      },
      {
        id: 'D26005048',
        code: 'D26005048',
        title: 'OB 2026 - Jay Ly - Waiting for document (TX)',
        shortTitle: 'OB - Jay Ly...',
        pipeline: 'Obamacare 2026',
        stage: 'Waiting for document (Obamacare 2026)',
        carrier: 'Ambetter',
        amount: '$0.00',
        closeDate: '10/20/2026',
        sellingState: 'Texas (TX)',
        dealOwnerName: 'Jay Ly',
        enrolledNpn: 'Jay Ly 20011862',
        brokerEffectiveDate: '2026-10-01',
        terminationDate: '2027-12-31',
        primaryMemberId: '',
        saleSupportStatus: 'In Review',
        numberMember: 1,
        consentFormStatus: 'Need send new form',
      },
      {
        id: 'D26005049',
        code: 'D26005049',
        title: 'OB 2026 - Khanh Nguyen - Ready to enroll (CA)',
        shortTitle: 'OB - Khanh Nguyen...',
        pipeline: 'Obamacare 2026',
        stage: 'Ready to Enroll (Obamacare 2026)',
        carrier: 'Blue Shield of California',
        amount: '$0.00',
        closeDate: '10/25/2026',
        sellingState: 'California (CA)',
        dealOwnerName: 'Khanh Nguyen',
        enrolledNpn: 'Anh Que Pham 20011862',
        brokerEffectiveDate: '2026-10-01',
        terminationDate: '2027-12-31',
        primaryMemberId: '',
        saleSupportStatus: 'Ready',
        numberMember: 1,
        consentFormStatus: 'Sent out',
      },
      {
        id: 'D26005050',
        code: 'D26005050',
        title: 'Medicare Advantage - Anya Nguyen - Auto Renew (TX)',
        shortTitle: 'Medicare - Anya Nguyen...',
        pipeline: 'Medicare 2026',
        stage: 'Auto Renew - Active (Medicare 2026)',
        carrier: 'Humana',
        amount: '$295.00',
        closeDate: '10/01/2026',
        sellingState: 'Texas (TX)',
        dealOwnerName: 'Anya Nguyen',
        enrolledNpn: 'Anya Nguyen 20188212',
        brokerEffectiveDate: '2026-09-01',
        terminationDate: '2027-12-31',
        primaryMemberId: 'MID-99218201',
        saleSupportStatus: 'Completed',
        numberMember: 1,
        consentFormStatus: 'Uploaded',
      },
      {
        id: 'D26005051',
        code: 'D26005051',
        title: 'Medicare Advantage - Sarah Thai - HRA Done Active (NC)',
        shortTitle: 'Medicare - Sarah Thai...',
        pipeline: 'Medicare 2026',
        stage: 'Enrolled - HRA Done - Active (Medicare 2026)',
        carrier: 'Cigna',
        amount: '$310.00',
        closeDate: '09/25/2026',
        sellingState: 'North Carolina (NC)',
        dealOwnerName: 'Sarah Thai',
        enrolledNpn: 'Sarah Thai 20119283',
        brokerEffectiveDate: '2026-09-01',
        terminationDate: '2027-12-31',
        primaryMemberId: 'MID-66192834',
        saleSupportStatus: 'Completed',
        numberMember: 1,
        consentFormStatus: 'Collected',
      },
    ];

    for (let i = 0; i < extraDealsData.length; i++) {
      const d = extraDealsData[i];
      const assignedContact = allContacts[i % allContacts.length];
      await prisma.deal.create({
        data: {
          ...d,
          contactId: assignedContact.id,
        },
      });
    }

    // Refresh deals list after creating extra deals
    const currentDeals = await prisma.deal.findMany();

    // Create Sample Tickets with realistic agents, due dates, stages
    const pipelineTypes = ['CLIENT_SUPPORT', 'PAYMENT', 'COLLECT_DOCUMENT', 'CHOOSE_DOCTOR', 'AGENT_SUPPORT'];
    const agents = ['Anya Nguyen', 'Sean Ngo', 'Ivy Le', 'Sarah Thai'];
    const sampleDates = ['2026-09-10', '2026-09-15', '2026-09-18', '2026-09-25', '2026-09-28', '2026-10-05'];
    let tcCount = 0;
    
    for (const pipeline of pipelineTypes) {
      for (let i = 0; i < 5; i++) {
        tcCount++;
        const contact = allContacts[Math.floor(Math.random() * allContacts.length)];
        const deal = currentDeals[Math.floor(Math.random() * currentDeals.length)];
        const agent = agents[(tcCount + i) % agents.length];
        const dueDate = sampleDates[tcCount % sampleDates.length];
        const status = i === 4 ? 'Closed' : (i === 3 ? 'In Progress' : 'Open');
        const stage = i % 2 === 0 ? 'Waiting on verification' : 'Waiting on contact';

        const ticket = await prisma.ticket.create({
          data: {
            id: `TC2699${tcCount}`,
            contactId: contact.id,
            dealId: deal.id,
            title: `${pipeline === 'COLLECT_DOCUMENT' ? 'Collect Documents for Upload' : pipeline === 'PAYMENT' ? 'Check Monthly Payment' : pipeline === 'CHOOSE_DOCTOR' ? 'Choose Doctor Request' : 'Client Support Request'} #${tcCount}`,
            pipeline: pipeline,
            status,
            stage,
            priority: ['High', 'Medium', 'Low'][i % 3],
            category: 'Support',
            ticketOwner: deal.dealOwnerName || 'Khanh Nguyen',
            serviceAgent: agent,
            dueDate,
          }
        });
        
        await prisma.ticketComment.create({
          data: {
            ticketId: ticket.id,
            content: `Ticket logged by ${agent}. Processing Post-Sale SLA.`,
            authorName: agent,
          }
        });
      }
    }

    // Create Sample Tasks with realistic assignees and due dates
    const sampleTasks = [
      {
        id: 'TSK-001',
        title: 'Follow up on marketplace consent form - Nguyen Van A',
        status: 'Pending',
        priority: 'High',
        assignedTo: 'Anya Nguyen',
        dueDate: '2026-09-18', // Overdue
        contactId: allContacts[0].id,
        dealId: currentDeals[0].id,
      },
      {
        id: 'TSK-002',
        title: 'Call client to confirm PCP doctor - Tran Thi B',
        status: 'Pending',
        priority: 'Medium',
        assignedTo: 'Anya Nguyen',
        dueDate: '2026-09-28',
        contactId: allContacts[1 % allContacts.length].id,
        dealId: currentDeals[1 % currentDeals.length].id,
      },
      {
        id: 'TSK-003',
        title: 'Request SSN proof verification document',
        status: 'Pending',
        priority: 'High',
        assignedTo: 'Sean Ngo',
        dueDate: '2026-09-15', // Overdue
        contactId: allContacts[2 % allContacts.length].id,
        dealId: currentDeals[2 % currentDeals.length].id,
      },
      {
        id: 'TSK-004',
        title: 'Verify first month premium payment status',
        status: 'Pending',
        priority: 'Low',
        assignedTo: 'Ivy Le',
        dueDate: '2026-09-30',
        contactId: allContacts[3 % allContacts.length].id,
        dealId: currentDeals[3 % currentDeals.length].id,
      },
      {
        id: 'TSK-005',
        title: 'Process refund dispute with BCBS',
        status: 'Completed',
        priority: 'High',
        assignedTo: 'Sarah Thai',
        dueDate: '2026-09-12',
        contactId: allContacts[4 % allContacts.length].id,
        dealId: currentDeals[4 % currentDeals.length].id,
      },
      {
        id: 'TSK-006',
        title: 'Update member ID in Marketplace portal',
        status: 'Pending',
        priority: 'Medium',
        assignedTo: 'Sarah Thai',
        dueDate: '2026-09-29',
        contactId: allContacts[0].id,
        dealId: currentDeals[0].id,
      },
      {
        id: 'TSK-007',
        title: 'Collect Citizenship document from client',
        status: 'Pending',
        priority: 'High',
        assignedTo: 'Sean Ngo',
        dueDate: '2026-09-27',
        contactId: allContacts[1 % allContacts.length].id,
        dealId: currentDeals[1 % currentDeals.length].id,
      },
      {
        id: 'TSK-008',
        title: 'Assist agent on special enrollment application',
        status: 'Pending',
        priority: 'Low',
        assignedTo: 'Ivy Le',
        dueDate: '2026-10-02',
        contactId: allContacts[2 % allContacts.length].id,
        dealId: currentDeals[2 % currentDeals.length].id,
      },
      {
        id: 'TSK-009',
        title: 'Contact client for PCP doctor selection',
        status: 'Pending',
        priority: 'Medium',
        assignedTo: 'Sarah Thai',
        dueDate: '2026-09-17', // Overdue
        contactId: allContacts[3 % allContacts.length].id,
        dealId: currentDeals[3 % currentDeals.length].id,
      },
      {
        id: 'TSK-010',
        title: 'Process address update in Marketplace portal',
        status: 'In Progress',
        priority: 'Low',
        assignedTo: 'Anya Nguyen',
        dueDate: '2026-10-04',
        contactId: allContacts[4 % allContacts.length].id,
        dealId: currentDeals[4 % currentDeals.length].id,
      },
      {
        id: 'TSK-011',
        title: 'Verify alien registration number and immigration docs',
        status: 'Pending',
        priority: 'High',
        assignedTo: 'Sean Ngo',
        dueDate: '2026-09-14', // Overdue
        contactId: allContacts[0].id,
        dealId: currentDeals[0].id,
      },
      {
        id: 'TSK-012',
        title: 'Follow up with Humana on billing reconciliation',
        status: 'Completed',
        priority: 'Medium',
        assignedTo: 'Ivy Le',
        dueDate: '2026-09-20',
        contactId: allContacts[1 % allContacts.length].id,
        dealId: currentDeals[1 % currentDeals.length].id,
      },
    ];

    for (const tsk of sampleTasks) {
      await prisma.task.create({ data: tsk });
    }

    // Create Sample Commissions
    const carriers = ['BCBS', 'Ambetter', 'Kaiser', 'UHC', 'Humana', 'Molina', 'Oscar', 'Aetna', 'Cigna', 'Blue Shield CA'];
    for (let i = 0; i < carriers.length; i++) {
      const deal = currentDeals[i % currentDeals.length];
      await prisma.commission.create({
        data: {
          dealId: deal.id,
          agentName: deal.dealOwnerName || 'Anya Nguyen',
          carrier: carriers[i],
          period: '2026-10',
          grossAmount: 30.00,
          netAmount: 30.00,
          status: ['PENDING', 'SETTLED'][i % 2],
        }
      });
    }
  }

  console.log('🎉 Seeding completed successfully! 10 full customer profiles ready.');
}

main()
  .catch((e) => {
    console.error('❌ Seeding failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
